name: markelliot/autosquash action
description: Enable automatic squash commits on PRs
branding:
  icon: git-merge
  color: blue

inputs:
  github-token:
    description: the GitHub token to use to change the PR state
    required: true
  pull-request:
    description: the pull request object to enable
    required: true

runs:
  using: composite
  steps:
    - name: Enable Automatic Squash Commit
      shell: bash
      # disabling and re-enabling ensures up-to-date subject and body of squash commit
      run: |
        gh pr merge --squash --disable-auto "${{ inputs.pull-request-number }}"
        gh pr merge --squash --auto "${{ inputs.pull-request-number }}" \
           --subject "${{ inputs.pull-request.title }} (#${{ inputs.pull-request.number }})" \
           --body "${{ inputs.pull-request.body }}"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
