name: markelliot/autosquash action
description: Enable automatic squash commits on PRs
branding:
  icon: git-merge
  color: blue

inputs:
  github-token:
    description: the GitHub token to use to change the PR state
    required: true
  pull-request-number:
    description: the number of the target pull request
    required: true
  squash-commit-title:
    description: the text to use as the squash commit title
    required: true
  squash-commit-message:
    description: the text to use as the squash commit message
    required: true
  required-label:
    description: require this label in order to enable automerge
    required: false
  do-not-merge-label:
    description: requiore that this label is not present to enable automerge
    required: false

runs:
  using: composite
  steps:
    - name: Enable Automatic Squash Commit
      shell: bash
      run: |
        function pr_has_label {
          if [[ -n "$(gh pr view --json labels --jq "select(.labels[].name | contains(\"$1\"))" "${{ inputs.pull-request-number }}")" ]]
          then
            echo "true"
          else
            echo "false"
          fi
        }

        # disabling and re-enabling ensures up-to-date subject and body of squash commit
        gh pr merge --squash --disable-auto "${{ inputs.pull-request-number }}"

        let ENABLE
        if [[ -n "${{ inputs.required-label}}" ]]
        then
          ENABLE=$(pr_has_label '${{ inputs.required-label }}')
        else
          ENABLE=true
        fi

        echo $ENABLE
      env:
        GH_TOKEN: ${{ inputs.github-token }}
